### ISSUE TITLE
Unable to identify any set of controllers that can actuate the specified joints

### ISSUE THREAD

**Issue by danielfann** [MatthewVerbryke/inmoov_ros#1]
**first I'm using Noetic, don't know if that's the reason.
code's downloaded and catkin ran fine.  I'm trying to simulate InMoov in Gazebo and control it by RViz.  As in your instruction, 2 steps:**
1) roslaunch inmoov_gazebo inmoov_world.launch
2) roslaunch inmoov_moveit moveit_planning_execution.launch

**In the 1st step, I first noticed that the robot head is placed in a wrong position (it's at the origin), and then I found errors messages in the terminal, which are:**
Error [Model.cc:311] Joint with name [head_tilt] in model with name [inmoov] has a name collision. Please rename this joint.
Error [Model.cc:311] Joint with name [jaw] in model with name [inmoov] has a name collision. Please rename this joint.
... ...
[ERROR] [1612744455.267236665, 0.147000000]: GazeboRosControlPlugin missing <legacyModeNS> while using DefaultRobotHWSim, defaults to true.
This setting assumes you have an old package with an old implementation of DefaultRobotHWSim, where the robotNamespace is disregarded and absolute paths are used instead.
If you do not want to fix this issue in an old package just set <legacyModeNS> to true.
... ...
[ERROR] [1612744455.709122871, 0.319000000]: Could not load controller 'right_arm_controller' because controller type 'position_controllers/JointTrajectoryController' does not exist.
[ERROR] [1612744455.709189616, 0.319000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [1612744456.710170, 1.143000]: Failed to load right_arm_controller
... ...

**In the 2nd step, RViz can be launched okay with the head in the correct position.  I can do plan, the animation showed the arm can move correctly, however, it seems execute can do nothing, no part moved.  the error message in the terminal is:**
[ERROR] [1612744849.928173690, 254.685000000]: Unable to identify any set of controllers that can actuate the specified joints: [ right_bicep_rotate right_elbow right_shoulder_side right_shoulder_up right_wrist ]
[ERROR] [1612744849.928207913, 254.685000000]: Known controllers and their joints:

**Comment by MatthewVerbryke** [comment]
Hello,

Looking at the error return, have you installed [ros_control](http://wiki.ros.org/ros_control), [ros_controller](http://wiki.ros.org/ros_controllers), and [gazebo_ros_pkgs?](http://wiki.ros.org/gazebo_ros_pkgs). These packages are required to run the controllers for the InMoov. (It's been a while since I worked on this package, and I've been meaning to come back and update it for newer versions of ROS)

**Comment by danielfann** [comment]
Yes, Matthew!  I found out I hadn't installed gazebo_ros_pkgs !!!  I just tried after the installation.  It works now.  Thank you for your reply.  Really appreciate it!

**Comment by MatthewVerbryke** [comment]
Okay, cool. This serves as a reminder that I need to go back and insert the required software in the README for this repository.
